apigee/ansible-apigee-hybrid-accelerator

playbook.yaml

Skipping  validate-cluster role due to issues found in the validate cluster job

feat: skipped validate-cluster role

---

roles/cert-manager/defaults/main.yml
roles/cert-manager/tasks/main.yml
vars/vars.yaml

Added ability to skip cert-manager install

feat: added support to skip cert-manager install

---

.github/workflows/build.yml
.github/workflows/static-checks.yml
.github/workflows/testing.yml
test/scipts/deploy_control_plane.sh
test/scipts/setup_workload_identity.sh
test/terraform/control-plane/backend.tf
test/terraform/control-plane/main.tf
test/terraform/control-plane/terraform.tfvars
test/terraform/control-plane/variables.tf

feat: added code for testing

---

.github/workflows/testing.yml

* Added Code deploy control plane

feat: updated github actions

---

roles/apigee-hybrid-overrides/templates/http_proxy.j2
roles/apigee-hybrid-overrides/templates/overrides.yaml.j2
vars/vars.yaml

feat: added support for http proxy credentials

---

roles/apigee-hybrid-overrides/templates/overrides.yaml.j2
vars/test.yaml

feat: updated overrides.yaml.j2 to support logger envvars

---

roles/validate-input-k8s-cluster/files/roles_map.json
roles/validate-input-k8s-cluster/files/validate_k8s_objects.py

added service account secret roles validations

---

Dockerfile
test/scripts/run_playbook.sh

feat: added oauth2client lib

---

Dockerfile
README.md
decommission.yaml
playbook.yaml
roles/apigee-custom-sc/defaults/main.yml
roles/apigee-custom-sc/meta/main.yml
roles/apigee-custom-sc/tasks/main.yml
roles/apigee-custom-sc/templates/sc.yaml.j2
roles/apigee-custom-sc/vars/main.yml
roles/apigee-hybrid-overrides/templates/overrides.yaml.j2
roles/validate-input-k8s-cluster/files/validate_k8s_objects.py
roles/validate-input-k8s-cluster/tasks/main.yml
roles/validate-input/files/input.schema.json
vars/test.yaml
vars/vars.yaml

Fixes #19 
- updated README for custom storage classes

Added support for customizing storage class

---

Dockerfile

Fixes  Issue with Image build 

fix: Update Dockerfile to use versioned gcloud alpine image

---

.github/workflows/testing.yml
README.md
vars/test.yaml

Upgrade form 1.10.3 to 1.11.1 test along with cert-manager upgrade .

feat: apigee 1.10.x to 1.11.x test

---

README.md
vars/test.yaml
vars/vars.yaml

updated vars to point to 1.12 images

feat: updated vars to point to 1.12 images

---

.github/workflows/static-checks.yml
.github/workflows/testing.yml

Update testing.yml to fix gh action versions

---

vars/test.yaml

Updated test.yaml

---

vars/test.yaml

feat: updated test.yaml to point to 1.12.1

---

roles/apigee-hybrid-overrides/templates/overrides.yaml.j2
vars/test.yaml
vars/vars.yaml

feat: added support for  control plane drz

---

test/terraform/runtime-plane-gke/terraform.tfvars
vars/test.yaml
vars/vars.yaml

feat: updated vars to 1.13.2

---

vars/test.yaml

feat: bumped apigee hybrid hotfix version

---

vars/test.yaml

feat: updated instance id

---

roles/apigee-hybrid-overrides/templates/overrides.yaml.j2
roles/validate-api-calls/tasks/main.yml
vars/test.yaml

feat: added support for multiple ingressGateways

---

vars/test.yaml

feat: bump test1 env pods to test scale

---

README.md

feat: updated the readme
